export const path = {
    PUBLIC:'/',
    PRIVATE:'/',
    HOME:'/home',
    LOGIN: '/login',
    REGISTER: '/register',
    ALL:'*',
    BOOKS:'/books',
    BORROW:'/borrow',
    ONE_BOOK:'/books/:book_id',
    GENRE: '/genre',
    AUTHOR: '/author',
    READER: '/reader',
    ADD_BORROW:'/borrow/add',
    DETAIL_BORROW:'/borrow/:id',
    REPORT:'/report',
    PARAMS:'/params',
}